apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awseventsources.sources.triggermesh.com
spec:
  group: sources.triggermesh.com
  names:
    kind: AwsEventSources
    listKind: AwsEventSourcesList
    plural: awseventsources
    singular: awseventsources
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
